language: node_js
node_js:
- stable
sudo: required
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
- sed -i "s/\/master\//\/$TRAVIS_BRANCH\//g" README.md
- npm run doc
after_success:
- scripts/jsdoc/publish.sh
cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-speech
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=sdks
before_deploy:
- npm run build
- npm install -g bx-blue-green
deploy:
- provider: releases
  api_key: $GH_TOKEN
  file:
  - dist/watson-speech.js
  - dist/watson-speech.min.js
  - dist/watson-speech.min.js.map
  skip_cleanup: true
  on:
    tags: true
    repo: watson-developer-cloud/speech-javascript-sdk
- provider: npm
  email: germanattanasio@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: watson-developer-cloud/speech-javascript-sdk
- provider: script
  script: cd examples/ && bx-blue-green-travis
  skip_cleanup: true
  on:
    branch: master
    repo: watson-developer-cloud/speech-javascript-sdk
- provider: script
  script: scripts/create_semver_tag.sh
  on:
    branch: master
    repo: watson-developer-cloud/speech-javascript-sdk
